[package]
name = "poscan-runtime"
version = "3.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A runtime that manages a set of grandpa authorities and supplies them to the client"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { version = "2.0", features = ["derive"], default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "1.4.0"
static_assertions = "1.1.0"

# Substrate packages
pallet-balances = { version = '3.0', default-features = false }
frame-executive = { version = '3.0', default-features = false }
frame-support = { version = '3.0', default-features = false }
frame-system = { version = '3.0', default-features = false }
pallet-grandpa = { version = '3.0', default-features = false }
pallet-randomness-collective-flip = { version = '3.0', default-features = false }
sp-api = { version = '3.0', default-features = false }
sp-block-builder = { version = '3.0', default-features = false }
sp-core = { version = '3.0', default-features = false }
sp-finality-grandpa = { version = '3.0', default-features = false }
sp-inherents = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }
sp-offchain = { version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-session = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }
sp-transaction-pool = { version = '3.0', default-features = false }
sp-version = { version = '3.0', default-features = false }
pallet-sudo = { version = '3.0', default-features = false }
pallet-timestamp = { version = '3.0', default-features = false }
pallet-transaction-payment = { version = '3.0', default-features = false }
sp-consensus-poscan = { path = "../../primitives/consensus/poscan", default-features = false }
pallet-poscan = { path = "../../pallets/poscan", default-features = false }
difficulty = { package = "pallet-difficulty", path = "../../frame/difficulty", default-features = false }
rewards = { package = "pallet-rewards", path = "../../frame/rewards", default-features = false }
lockdrop = { package = "pallet-lockdrop", path = "../../frame/lockdrop", default-features = false }
treasury = { package = "pallet-treasury", version="3.0", default-features = false }
collective = { package = "pallet-collective",version="3.0", default-features = false }
bounties = { package = "pallet-bounties", version="3.0", default-features = false }
sp-arithmetic = { version="3.0", default-features = false }

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[features]
default = ["std"]
std = [
	"pallet-balances/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-grandpa/std",
	"parity-scale-codec/std",
	"pallet-randomness-collective-flip/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"sp-consensus-poscan/std",
	"pallet-poscan/std",
	"treasury/std",
	"collective/std",
	"bounties/std",
	"sp-arithmetic/std",
]
