[book]
authors = ['Amar Singh', 'Joshy Orndorff', 'Jimmy Chu', 'Others']
language = "en"
multilingual = false
src = "text"
title = "Substrate Recipes"
description = "A Hands-On Cookbook for Aspiring Blockchain Chefs"

[output.html]
cname = "substrate.recipes"