[workspace]
members = [
    "runtime",
    "nodes/poscan-consensus",
    "precompiles/assets-conversion",
    "precompiles/poscan",
    "precompiles/identity",
    "pallets/serial-numbers",
]
resolver = "2"

[profile.release]
panic = "unwind"