[workspace]
members = [
	"runtimes/poscan-runtime",
	"nodes/poscan-consensus",
    "consensus/poscan_grid2d",
	"traits/account-set",
	"consensus/poscan",
	"pallets/poscan",
	"primitives/consensus/poscan",

	"pallets/rewards",
	# "pallets/lockdrop",
]
librocksdb-sys = "6.17.3"
