version: "3.9"

services:
  miner:
    container_name: "miner"
    build:
      context: .
      dockerfile: docker/miner.Dockerfile
    links:
      - "node1:node1"

  node1:
    container_name: "node1"
    build:
      context: .
      dockerfile: docker/node.Dockerfile


  node2:
    container_name: "node2"
    build:
      context: .
      dockerfile: docker/node.Dockerfile

networks:
  node1_net:
  node2_net:
