version: "3.9"

services:
  miner:
    container_name: "miner"
    build:
      context: .
      dockerfile: docker/miner.Dockerfile
    links:
      - "node:node"

  node:
    container_name: "node"
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - /var/chain
    ports:
      - "9944:9944"
      - "9933:9933"
