[package]
name = "pallet-rewards"
version = "2.8.0"
authors = ["Wei Tang <wei@that.world>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.1.0", default-features = false, features = ["derive"] }
sp-runtime = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
sp-std = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
sp-inherents = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
sp-consensus-pow = { version="0.9", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
sp-consensus-poscan = { version = "0.9.0", package = "sp-consensus-poscan", default-features = false, path = "../../primitives/consensus/poscan" }
frame-support = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
frame-system = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }

# Benchmarking
frame-benchmarking = { version="3.0", default-features = false, optional = true, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }

[dev-dependencies]
sp-core = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
sp-io = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }
pallet-balances = { version="3.0", default-features = false, git = "https://github.com/3Dpass/substrate.git", branch = "3dp_v3" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-inherents/std",
	"sp-consensus-pow/std",
	"frame-support/std",
	"frame-system/std",
	"sp-consensus-poscan/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
]
