[package]
name = "fc-db"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Frontier database backend"
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.17"
parking_lot = "0.12.1"

# Parity
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
kvdb-rocksdb = { version = "0.15.2", optional = true }
parity-db = { version = "0.3.16", optional = true }

# Substrate
sc-client-db = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
sp-database = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }

# Frontier
fp-storage = { version = "2.0.0-dev", path = "../../primitives/storage" }

[features]
default = ["kvdb-rocksdb", "parity-db"]

[dev-dependencies]
futures = "0.3"
sc-block-builder = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
sc-client-db = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7", features = ["rocksdb"] }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
substrate-test-runtime-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "b0777b4c7f7" }
tempfile = "3.3.0"
