name: Test Code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test-ci # always want to including test-ci for testing gh-action
    paths-ignore:
      - 'README.md'

jobs:
  test-code:
    name: Test
    strategy:
      matrix:
        toolchain:
          - stable
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:              full
      CARGO_INCREMENTAL:           0

    steps:
      - name:                      Cancel previous runs
        uses:                      styfle/cancel-workflow-action@0.9.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          fetch-depth:             5
          submodules:              recursive

      - name:                      Rust Cache
        uses:                      Swatinem/rust-cache@v1

      - name:                      Install toolchain
        uses:                      actions-rs/toolchain@v1
        with:
          profile:                 minimal
          toolchain:               nightly-2021-08-31
          components:              rustfmt, clippy
          target:                  wasm32-unknown-unknown
          override:                true
          default:                 true

      - name:                      Rust version
        shell:                     bash
        run:                       |
          rustup show
          rustup +nightly show

      ## --- Test stage ---

      - name:                      Run clippy
        run:                       |
          cargo +nightly-2021-08-31 clippy -- -D warnings

      - name:                      Run all recipes tests
        uses:                      actions-rs/cargo@v1
        with:
          command:                 test
          args:                    --all --verbose
